### ISSUE TITLE
Error Module: Docs | Command: query docs received-documents, received-receipts, sent-documents & sent-receipts

### ISSUE THREAD

**Issue by BenWolfaardt** [commercionetwork/commercionetwork#252]
## Summary of Bug

The below subcomamands for `query docs <below_command>` do not work: 

* `received-documents`
* `received-receipts`
* `sent-documents`
* `sent-receipts`

When performed they receive the following errors:

### `received-documents`

```s
./commercionetworkd query docs received-documents \
  did:com:17zx4vs4fhy7c2yv4gzq5u9uqutlzqv7xyq9y38 \
  --chain-id commercionetwork
```

error

```s
Could not get received documents by user: 
 no RPC client is defined in offline modeError: Marshal called with nil
```

### `received-receipts`

```s
./commercionetworkd query docs received-receipts \
  did:com:17zx4vs4fhy7c2yv4gzq5u9uqutlzqv7xyq9y38 \
  --chain-id commercionetwork
```

error

```s
Could not get any received receipt for the given user or uuid: 
 no RPC client is defined in offline modeError: Marshal called with nil
```

### `sent-documents`

```s
./commercionetworkd query docs sent-documents, \
  did:com:17zx4vs4fhy7c2yv4gzq5u9uqutlzqv7xyq9y38 \
  --chain-id commercionetwork
```

error

```s
Could not get any received receipt for the given user or uuid: 
 no RPC client is defined in offline modeError: Marshal called with nil
```

### `sent-receipts`

```s
./commercionetworkd query docs sent-receipts \
  did:com:17zx4vs4fhy7c2yv4gzq5u9uqutlzqv7xyq9y38 \
  --chain-id commercionetwork
```

error

```s
Could not get any sent receipt for the given user: 
 no RPC client is defined in offline modeError: Marshal called with nil
```

And this after having successfully performed the following commands `commercionetworkd tx docs share [recipient] [document-uuid] [document-metadata-uri] [metadata-schema-uri] [metadata-schema-version] [document-content-uri] [checksum-value] [checksum-algorithm]  [flags]` as well as `./commercionetworkd tx docs send-receipt [recipient] [tx-hash] [document-uuid] [proof] [flags]`.

### Example of Desired Parameters 
```bash
[user-addr]
[flags
```

## Version

git branch `main-3.0`

### Perform `tx docs share`

```bash
./commercionetworkd tx docs share \
 did:com:17zx4vs4fhy7c2yv4gzq5u9uqutlzqv7xyq9y38 \
 93469347-8740-4b48-a417-10bb9f36ee98 \
 http://content.uri \
 http://schema.uri \
 1.0.0 \
 http://content.uri \
 2cf24dba5fb0a30e26e83b2ac5b9e29e1b161e5c1fa7425e73043362938b9824 \
 sha-256 \
  --from did:com:1q7hszn4gtwdrpylldw32ex2p7cpd4qvj00yg8t \
  --node http://0.0.0.0:26657 \
  --chain-id commercionetwork \
  --fees 10000ucommercio \
  -y
```

Response: 

```json
{
  "height": "6328",
  "txhash": "6C6F23AACD69041AF668D2CA53BBE7E7A3DAD8B39022AFDA340EA3644F730A0A",
  "codespace": "",
  "code": 0,
  "data": "0A370A0D7368617265446F63756D656E7412260A2439333436393334372D383734302D346234382D613431372D313062623966333665653938",
  "raw_log": "[{\"events\":[{\"type\":\"message\",\"attributes\":[{\"key\":\"action\",\"value\":\"shareDocument\"}]},{\"type\":\"new_saved_document\",\"attributes\":[{\"key\":\"sender\",\"value\":\"did:com:1q7hszn4gtwdrpylldw32ex2p7cpd4qvj00yg8t\"},{\"key\":\"doc_id\",\"value\":\"93469347-8740-4b48-a417-10bb9f36ee98\"},{\"key\":\"receiver_0\",\"value\":\"did:com:17zx4vs4fhy7c2yv4gzq5u9uqutlzqv7xyq9y38\"}]}]}]",
  "logs": [
    {
      "msg_index": 0,
      "log": "",
      "events": [
        {
          "type": "message",
          "attributes": [
            {
              "key": "action",
              "value": "shareDocument"
            }
          ]
        },
        {
          "type": "new_saved_document",
          "attributes": [
            {
              "key": "sender",
              "value": "did:com:1q7hszn4gtwdrpylldw32ex2p7cpd4qvj00yg8t"
            },
            {
              "key": "doc_id",
              "value": "93469347-8740-4b48-a417-10bb9f36ee98"
            },
            {
              "key": "receiver_0",
              "value": "did:com:17zx4vs4fhy7c2yv4gzq5u9uqutlzqv7xyq9y38"
            }
          ]
        }
      ]
    }
  ],
  "info": "",
  "gas_wanted": "200000",
  "gas_used": "77575",
  "tx": null,
  "timestamp": ""
}
```

### Perform `tx docs send-receipt`

```bash
./commercionetworkd tx docs send-receipt \
 did:com:17zx4vs4fhy7c2yv4gzq5u9uqutlzqv7xyq9y38 \
 6C6F23AACD69041AF668D2CA53BBE7E7A3DAD8B39022AFDA340EA3644F730A0A \
 93469347-8740-4b48-a417-10bb9f36ee98 \
 sha-256 \
  --from did:com:1q7hszn4gtwdrpylldw32ex2p7cpd4qvj00yg8t \
  --node http://0.0.0.0:26657 \
  --chain-id commercionetwork \
  --fees 10000ucommercio \
  -y
```

Response: 

```json
{
  "height": "6508",
  "txhash": "E96CB864D89A3C97DDB036B8A1A06F80F1D6C4248A9F865BC3D626BF92370D82",
  "codespace": "",
  "code": 0,
  "data": "0A3D0A1373656E64446F63756D656E745265636569707412260A2461323538646333332D356461362D346133332D383262662D353065633964353562363933",
  "raw_log": "[{\"events\":[{\"type\":\"message\",\"attributes\":[{\"key\":\"action\",\"value\":\"sendDocumentReceipt\"},{\"key\":\"sender\",\"value\":\"did:com:1q7hszn4gtwdrpylldw32ex2p7cpd4qvj00yg8t\"}]},{\"type\":\"new_saved_receipt\",\"attributes\":[{\"key\":\"receipt_id\",\"value\":\"a258dc33-5da6-4a33-82bf-50ec9d55b693\"},{\"key\":\"document_id\",\"value\":\"93469347-8740-4b48-a417-10bb9f36ee98\"},{\"key\":\"sender\",\"value\":\"did:com:1q7hszn4gtwdrpylldw32ex2p7cpd4qvj00yg8t\"},{\"key\":\"recipient\",\"value\":\"did:com:17zx4vs4fhy7c2yv4gzq5u9uqutlzqv7xyq9y38\"}]}]}]",
  "logs": [
    {
      "msg_index": 0,
      "log": "",
      "events": [
        {
          "type": "message",
          "attributes": [
            {
              "key": "action",
              "value": "sendDocumentReceipt"
            },
            {
              "key": "sender",
              "value": "did:com:1q7hszn4gtwdrpylldw32ex2p7cpd4qvj00yg8t"
            }
          ]
        },
        {
          "type": "new_saved_receipt",
          "attributes": [
            {
              "key": "receipt_id",
              "value": "a258dc33-5da6-4a33-82bf-50ec9d55b693"
            },
            {
              "key": "document_id",
              "value": "93469347-8740-4b48-a417-10bb9f36ee98"
            },
            {
              "key": "sender",
              "value": "did:com:1q7hszn4gtwdrpylldw32ex2p7cpd4qvj00yg8t"
            },
            {
              "key": "recipient",
              "value": "did:com:17zx4vs4fhy7c2yv4gzq5u9uqutlzqv7xyq9y38"
            }
          ]
        }
      ]
    }
  ],
  "info": "",
  "gas_wanted": "200000",
  "gas_used": "73626",
  "tx": null,
  "timestamp": ""
}
```

Noting that in the error messages that it either stipulates `Could not get any sent receipt for the given user: ` or `Could not get any received receipt for the given user or uuid:` it seems that there might be an error with what is stated as `expected` arguments and those which are `actually` required?

**Comment by BenWolfaardt** [comment]
@marcotradenet I don't seem to be able to assign someone if I try to do so after having created the issue, this is to inform you of the issue.

**Comment by BenWolfaardt** [comment]
@SerigneCheikh98 please note that issue #255 is essentially the same as this, so once you've solved this, you can implement the same solution for issue #255

**Comment by marcotradenet** [comment]
@BenWolfaardt the errors should be fixed. Please try again.

**Comment by BenWolfaardt** [comment]
@marcotradenet, @SerigneCheikh98 unfortunately, after further investigation the issue doesn't yet seem to be resolved as the same errors are still occurring.

**Comment by SerigneCheikh98** [comment]
@BenWolfaardt the bug has been fixed on branch `cheikh/fix-documents`, now it works finely. Please try again.

**Comment by BenWolfaardt** [comment]
Wonderful, works great thanks @SerigneCheikh98
